/*
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCosaDslScopeProvider extends DelegatingScopeProvider {
}
