/**
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.ui;

import fr.univnantes.asa.xtext.ui.AbstractCosaDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CosaDslUiModule extends AbstractCosaDslUiModule {
  public CosaDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
