/*
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.univnantes.asa.xtext.ide.contentassist.antlr.internal.InternalCosaDslParser;
import fr.univnantes.asa.xtext.services.CosaDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class CosaDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CosaDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CosaDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPortAccess().getAlternatives(), "rule__Port__Alternatives");
			builder.put(grammarAccess.getServiceAccess().getAlternatives(), "rule__Service__Alternatives");
			builder.put(grammarAccess.getRoleAccess().getAlternatives(), "rule__Role__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getGroup(), "rule__CompositeConfiguration__Group__0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getGroup_4(), "rule__CompositeConfiguration__Group_4__0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getGroup_6(), "rule__CompositeConfiguration__Group_6__0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getGroup_8(), "rule__CompositeConfiguration__Group_8__0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getGroup_9(), "rule__CompositeConfiguration__Group_9__0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getGroup_9_1(), "rule__CompositeConfiguration__Group_9_1__0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getGroup_11(), "rule__CompositeConfiguration__Group_11__0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getGroup_12(), "rule__CompositeConfiguration__Group_12__0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getGroup_12_1(), "rule__CompositeConfiguration__Group_12_1__0");
			builder.put(grammarAccess.getConfigurationAccess().getGroup(), "rule__Configuration__Group__0");
			builder.put(grammarAccess.getConfigurationAccess().getGroup_4(), "rule__Configuration__Group_4__0");
			builder.put(grammarAccess.getConfigurationAccess().getGroup_6(), "rule__Configuration__Group_6__0");
			builder.put(grammarAccess.getConfigurationAccess().getGroup_8(), "rule__Configuration__Group_8__0");
			builder.put(grammarAccess.getConfigurationAccess().getGroup_9(), "rule__Configuration__Group_9__0");
			builder.put(grammarAccess.getConfigurationAccess().getGroup_9_1(), "rule__Configuration__Group_9_1__0");
			builder.put(grammarAccess.getConfigurationAccess().getGroup_11(), "rule__Configuration__Group_11__0");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getGroup(), "rule__SimpleConfiguration__Group__0");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getGroup_4(), "rule__SimpleConfiguration__Group_4__0");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getGroup_7(), "rule__SimpleConfiguration__Group_7__0");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getGroup_10(), "rule__SimpleConfiguration__Group_10__0");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getGroup_11(), "rule__SimpleConfiguration__Group_11__0");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getGroup_11_1(), "rule__SimpleConfiguration__Group_11_1__0");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getGroup_13(), "rule__SimpleConfiguration__Group_13__0");
			builder.put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
			builder.put(grammarAccess.getComponentAccess().getGroup_4(), "rule__Component__Group_4__0");
			builder.put(grammarAccess.getComponentAccess().getGroup_6(), "rule__Component__Group_6__0");
			builder.put(grammarAccess.getConnectorAccess().getGroup(), "rule__Connector__Group__0");
			builder.put(grammarAccess.getPort_ImplAccess().getGroup(), "rule__Port_Impl__Group__0");
			builder.put(grammarAccess.getBindingAccess().getGroup(), "rule__Binding__Group__0");
			builder.put(grammarAccess.getAttachementAccess().getGroup(), "rule__Attachement__Group__0");
			builder.put(grammarAccess.getService_ImplAccess().getGroup(), "rule__Service_Impl__Group__0");
			builder.put(grammarAccess.getRequiredServiceAccess().getGroup(), "rule__RequiredService__Group__0");
			builder.put(grammarAccess.getProvidedServiceAccess().getGroup(), "rule__ProvidedService__Group__0");
			builder.put(grammarAccess.getRole_ImplAccess().getGroup(), "rule__Role_Impl__Group__0");
			builder.put(grammarAccess.getRequiredRoleAccess().getGroup(), "rule__RequiredRole__Group__0");
			builder.put(grammarAccess.getProvidedRoleAccess().getGroup(), "rule__ProvidedRole__Group__0");
			builder.put(grammarAccess.getRequiredPortAccess().getGroup(), "rule__RequiredPort__Group__0");
			builder.put(grammarAccess.getProvidedPortAccess().getGroup(), "rule__ProvidedPort__Group__0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getNameAssignment_1(), "rule__CompositeConfiguration__NameAssignment_1");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getComponentsAssignment_3(), "rule__CompositeConfiguration__ComponentsAssignment_3");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getComponentsAssignment_4_1(), "rule__CompositeConfiguration__ComponentsAssignment_4_1");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getConnectorsAssignment_5(), "rule__CompositeConfiguration__ConnectorsAssignment_5");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getConnectorsAssignment_6_1(), "rule__CompositeConfiguration__ConnectorsAssignment_6_1");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getPortsAssignment_7(), "rule__CompositeConfiguration__PortsAssignment_7");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getPortsAssignment_8_1(), "rule__CompositeConfiguration__PortsAssignment_8_1");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getBindingsAssignment_9_0(), "rule__CompositeConfiguration__BindingsAssignment_9_0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getBindingsAssignment_9_1_1(), "rule__CompositeConfiguration__BindingsAssignment_9_1_1");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getAttachementsAssignment_10(), "rule__CompositeConfiguration__AttachementsAssignment_10");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getAttachementsAssignment_11_1(), "rule__CompositeConfiguration__AttachementsAssignment_11_1");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getConfigurationsAssignment_12_0(), "rule__CompositeConfiguration__ConfigurationsAssignment_12_0");
			builder.put(grammarAccess.getCompositeConfigurationAccess().getConfigurationsAssignment_12_1_1(), "rule__CompositeConfiguration__ConfigurationsAssignment_12_1_1");
			builder.put(grammarAccess.getConfigurationAccess().getNameAssignment_1(), "rule__Configuration__NameAssignment_1");
			builder.put(grammarAccess.getConfigurationAccess().getComponentsAssignment_3(), "rule__Configuration__ComponentsAssignment_3");
			builder.put(grammarAccess.getConfigurationAccess().getComponentsAssignment_4_1(), "rule__Configuration__ComponentsAssignment_4_1");
			builder.put(grammarAccess.getConfigurationAccess().getConnectorsAssignment_5(), "rule__Configuration__ConnectorsAssignment_5");
			builder.put(grammarAccess.getConfigurationAccess().getConnectorsAssignment_6_1(), "rule__Configuration__ConnectorsAssignment_6_1");
			builder.put(grammarAccess.getConfigurationAccess().getPortsAssignment_7(), "rule__Configuration__PortsAssignment_7");
			builder.put(grammarAccess.getConfigurationAccess().getPortsAssignment_8_1(), "rule__Configuration__PortsAssignment_8_1");
			builder.put(grammarAccess.getConfigurationAccess().getBindingsAssignment_9_0(), "rule__Configuration__BindingsAssignment_9_0");
			builder.put(grammarAccess.getConfigurationAccess().getBindingsAssignment_9_1_1(), "rule__Configuration__BindingsAssignment_9_1_1");
			builder.put(grammarAccess.getConfigurationAccess().getAttachementsAssignment_10(), "rule__Configuration__AttachementsAssignment_10");
			builder.put(grammarAccess.getConfigurationAccess().getAttachementsAssignment_11_1(), "rule__Configuration__AttachementsAssignment_11_1");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getNameAssignment_1(), "rule__SimpleConfiguration__NameAssignment_1");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getComponentsAssignment_3(), "rule__SimpleConfiguration__ComponentsAssignment_3");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getComponentsAssignment_4_1(), "rule__SimpleConfiguration__ComponentsAssignment_4_1");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getConnectorsAssignment_6(), "rule__SimpleConfiguration__ConnectorsAssignment_6");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getConnectorsAssignment_7_1(), "rule__SimpleConfiguration__ConnectorsAssignment_7_1");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getPortsAssignment_9(), "rule__SimpleConfiguration__PortsAssignment_9");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getPortsAssignment_10_1(), "rule__SimpleConfiguration__PortsAssignment_10_1");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getBindingsAssignment_11_0(), "rule__SimpleConfiguration__BindingsAssignment_11_0");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getBindingsAssignment_11_1_1(), "rule__SimpleConfiguration__BindingsAssignment_11_1_1");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getAttachementsAssignment_12(), "rule__SimpleConfiguration__AttachementsAssignment_12");
			builder.put(grammarAccess.getSimpleConfigurationAccess().getAttachementsAssignment_13_1(), "rule__SimpleConfiguration__AttachementsAssignment_13_1");
			builder.put(grammarAccess.getComponentAccess().getNameAssignment_1(), "rule__Component__NameAssignment_1");
			builder.put(grammarAccess.getComponentAccess().getPortsAssignment_3(), "rule__Component__PortsAssignment_3");
			builder.put(grammarAccess.getComponentAccess().getPortsAssignment_4_1(), "rule__Component__PortsAssignment_4_1");
			builder.put(grammarAccess.getComponentAccess().getServicesAssignment_5(), "rule__Component__ServicesAssignment_5");
			builder.put(grammarAccess.getComponentAccess().getServicesAssignment_6_1(), "rule__Component__ServicesAssignment_6_1");
			builder.put(grammarAccess.getConnectorAccess().getNameAssignment_1(), "rule__Connector__NameAssignment_1");
			builder.put(grammarAccess.getConnectorAccess().getRolesAssignment_4(), "rule__Connector__RolesAssignment_4");
			builder.put(grammarAccess.getConnectorAccess().getRolesAssignment_6(), "rule__Connector__RolesAssignment_6");
			builder.put(grammarAccess.getPort_ImplAccess().getNameAssignment_2(), "rule__Port_Impl__NameAssignment_2");
			builder.put(grammarAccess.getBindingAccess().getPortProvidedAssignment_2(), "rule__Binding__PortProvidedAssignment_2");
			builder.put(grammarAccess.getBindingAccess().getPortRequiredAssignment_3(), "rule__Binding__PortRequiredAssignment_3");
			builder.put(grammarAccess.getAttachementAccess().getRoleAssignment_2(), "rule__Attachement__RoleAssignment_2");
			builder.put(grammarAccess.getAttachementAccess().getPortAssignment_4(), "rule__Attachement__PortAssignment_4");
			builder.put(grammarAccess.getService_ImplAccess().getNameAssignment_2(), "rule__Service_Impl__NameAssignment_2");
			builder.put(grammarAccess.getRequiredServiceAccess().getNameAssignment_2(), "rule__RequiredService__NameAssignment_2");
			builder.put(grammarAccess.getProvidedServiceAccess().getNameAssignment_2(), "rule__ProvidedService__NameAssignment_2");
			builder.put(grammarAccess.getRole_ImplAccess().getNameAssignment_2(), "rule__Role_Impl__NameAssignment_2");
			builder.put(grammarAccess.getRequiredRoleAccess().getNameAssignment_2(), "rule__RequiredRole__NameAssignment_2");
			builder.put(grammarAccess.getProvidedRoleAccess().getNameAssignment_2(), "rule__ProvidedRole__NameAssignment_2");
			builder.put(grammarAccess.getRequiredPortAccess().getNameAssignment_2(), "rule__RequiredPort__NameAssignment_2");
			builder.put(grammarAccess.getProvidedPortAccess().getNameAssignment_2(), "rule__ProvidedPort__NameAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CosaDslGrammarAccess grammarAccess;

	@Override
	protected InternalCosaDslParser createParser() {
		InternalCosaDslParser result = new InternalCosaDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CosaDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CosaDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
