/**
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.ide;

import fr.univnantes.asa.xtext.ide.AbstractCosaDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CosaDslIdeModule extends AbstractCosaDslIdeModule {
}
