/**
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.univnantes.asa.xtext.CosaDslRuntimeModule;
import fr.univnantes.asa.xtext.CosaDslStandaloneSetup;
import fr.univnantes.asa.xtext.ide.CosaDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CosaDslIdeSetup extends CosaDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    CosaDslRuntimeModule _cosaDslRuntimeModule = new CosaDslRuntimeModule();
    CosaDslIdeModule _cosaDslIdeModule = new CosaDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_cosaDslRuntimeModule, _cosaDslIdeModule));
  }
}
