/**
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.ui.contentassist;

import fr.univnantes.asa.xtext.ui.contentassist.AbstractCosaDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CosaDslProposalProvider extends AbstractCosaDslProposalProvider {
}
