/*
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CosaDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class CompositeConfigurationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.CompositeConfiguration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompositeConfigurationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cComponentsComponentParserRuleCall_3_0 = (RuleCall)cComponentsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cComponentsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cComponentsComponentParserRuleCall_4_1_0 = (RuleCall)cComponentsAssignment_4_1.eContents().get(0);
		private final Assignment cConnectorsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cConnectorsConnectorParserRuleCall_5_0 = (RuleCall)cConnectorsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cConnectorsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cConnectorsConnectorParserRuleCall_6_1_0 = (RuleCall)cConnectorsAssignment_6_1.eContents().get(0);
		private final Assignment cPortsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPortsPortParserRuleCall_7_0 = (RuleCall)cPortsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cPortsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cPortsPortParserRuleCall_8_1_0 = (RuleCall)cPortsAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Assignment cBindingsAssignment_9_0 = (Assignment)cGroup_9.eContents().get(0);
		private final RuleCall cBindingsBindingParserRuleCall_9_0_0 = (RuleCall)cBindingsAssignment_9_0.eContents().get(0);
		private final Group cGroup_9_1 = (Group)cGroup_9.eContents().get(1);
		private final Keyword cCommaKeyword_9_1_0 = (Keyword)cGroup_9_1.eContents().get(0);
		private final Assignment cBindingsAssignment_9_1_1 = (Assignment)cGroup_9_1.eContents().get(1);
		private final RuleCall cBindingsBindingParserRuleCall_9_1_1_0 = (RuleCall)cBindingsAssignment_9_1_1.eContents().get(0);
		private final Assignment cAttachementsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cAttachementsAttachementParserRuleCall_10_0 = (RuleCall)cAttachementsAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cAttachementsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cAttachementsAttachementParserRuleCall_11_1_0 = (RuleCall)cAttachementsAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Assignment cConfigurationsAssignment_12_0 = (Assignment)cGroup_12.eContents().get(0);
		private final RuleCall cConfigurationsConfigurationParserRuleCall_12_0_0 = (RuleCall)cConfigurationsAssignment_12_0.eContents().get(0);
		private final Group cGroup_12_1 = (Group)cGroup_12.eContents().get(1);
		private final Keyword cCommaKeyword_12_1_0 = (Keyword)cGroup_12_1.eContents().get(0);
		private final Assignment cConfigurationsAssignment_12_1_1 = (Assignment)cGroup_12_1.eContents().get(1);
		private final RuleCall cConfigurationsConfigurationParserRuleCall_12_1_1_0 = (RuleCall)cConfigurationsAssignment_12_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//CompositeConfiguration:
		//	'CompositeConfiguration'
		//	name=EString
		//	'={'
		//	components+=Component ("," components+=Component)*
		//	connectors+=Connector ("," connectors+=Connector)*
		//	ports+=Port ("," ports+=Port)* (bindings+=Binding ("," bindings+=Binding)*)*
		//	attachements+=Attachement ("," attachements+=Attachement)* (configurations+=Configuration (","
		//	configurations+=Configuration)*)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'CompositeConfiguration' name=EString '={' components+=Component ("," components+=Component)* connectors+=Connector (","
		//connectors+=Connector)* ports+=Port ("," ports+=Port)* (bindings+=Binding ("," bindings+=Binding)*)*
		//attachements+=Attachement ("," attachements+=Attachement)* (configurations+=Configuration (","
		//configurations+=Configuration)*)* '}'
		public Group getGroup() { return cGroup; }
		
		//'CompositeConfiguration'
		public Keyword getCompositeConfigurationKeyword_0() { return cCompositeConfigurationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'={'
		public Keyword getEqualsSignLeftCurlyBracketKeyword_2() { return cEqualsSignLeftCurlyBracketKeyword_2; }
		
		//components+=Component
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_0() { return cComponentsComponentParserRuleCall_3_0; }
		
		//("," components+=Component)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//components+=Component
		public Assignment getComponentsAssignment_4_1() { return cComponentsAssignment_4_1; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_4_1_0() { return cComponentsComponentParserRuleCall_4_1_0; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_5() { return cConnectorsAssignment_5; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_5_0() { return cConnectorsConnectorParserRuleCall_5_0; }
		
		//("," connectors+=Connector)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_6_1() { return cConnectorsAssignment_6_1; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_6_1_0() { return cConnectorsConnectorParserRuleCall_6_1_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_7() { return cPortsAssignment_7; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_7_0() { return cPortsPortParserRuleCall_7_0; }
		
		//("," ports+=Port)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_8_1() { return cPortsAssignment_8_1; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_8_1_0() { return cPortsPortParserRuleCall_8_1_0; }
		
		//(bindings+=Binding ("," bindings+=Binding)*)*
		public Group getGroup_9() { return cGroup_9; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_9_0() { return cBindingsAssignment_9_0; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_9_0_0() { return cBindingsBindingParserRuleCall_9_0_0; }
		
		//("," bindings+=Binding)*
		public Group getGroup_9_1() { return cGroup_9_1; }
		
		//","
		public Keyword getCommaKeyword_9_1_0() { return cCommaKeyword_9_1_0; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_9_1_1() { return cBindingsAssignment_9_1_1; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_9_1_1_0() { return cBindingsBindingParserRuleCall_9_1_1_0; }
		
		//attachements+=Attachement
		public Assignment getAttachementsAssignment_10() { return cAttachementsAssignment_10; }
		
		//Attachement
		public RuleCall getAttachementsAttachementParserRuleCall_10_0() { return cAttachementsAttachementParserRuleCall_10_0; }
		
		//("," attachements+=Attachement)*
		public Group getGroup_11() { return cGroup_11; }
		
		//","
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//attachements+=Attachement
		public Assignment getAttachementsAssignment_11_1() { return cAttachementsAssignment_11_1; }
		
		//Attachement
		public RuleCall getAttachementsAttachementParserRuleCall_11_1_0() { return cAttachementsAttachementParserRuleCall_11_1_0; }
		
		//(configurations+=Configuration ("," configurations+=Configuration)*)*
		public Group getGroup_12() { return cGroup_12; }
		
		//configurations+=Configuration
		public Assignment getConfigurationsAssignment_12_0() { return cConfigurationsAssignment_12_0; }
		
		//Configuration
		public RuleCall getConfigurationsConfigurationParserRuleCall_12_0_0() { return cConfigurationsConfigurationParserRuleCall_12_0_0; }
		
		//("," configurations+=Configuration)*
		public Group getGroup_12_1() { return cGroup_12_1; }
		
		//","
		public Keyword getCommaKeyword_12_1_0() { return cCommaKeyword_12_1_0; }
		
		//configurations+=Configuration
		public Assignment getConfigurationsAssignment_12_1_1() { return cConfigurationsAssignment_12_1_1; }
		
		//Configuration
		public RuleCall getConfigurationsConfigurationParserRuleCall_12_1_1_0() { return cConfigurationsConfigurationParserRuleCall_12_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class ConfigurationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Configuration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConfigurationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cComponentsComponentParserRuleCall_3_0 = (RuleCall)cComponentsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cComponentsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cComponentsComponentParserRuleCall_4_1_0 = (RuleCall)cComponentsAssignment_4_1.eContents().get(0);
		private final Assignment cConnectorsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cConnectorsConnectorParserRuleCall_5_0 = (RuleCall)cConnectorsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cConnectorsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cConnectorsConnectorParserRuleCall_6_1_0 = (RuleCall)cConnectorsAssignment_6_1.eContents().get(0);
		private final Assignment cPortsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPortsPortParserRuleCall_7_0 = (RuleCall)cPortsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cPortsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cPortsPortParserRuleCall_8_1_0 = (RuleCall)cPortsAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Assignment cBindingsAssignment_9_0 = (Assignment)cGroup_9.eContents().get(0);
		private final RuleCall cBindingsBindingParserRuleCall_9_0_0 = (RuleCall)cBindingsAssignment_9_0.eContents().get(0);
		private final Group cGroup_9_1 = (Group)cGroup_9.eContents().get(1);
		private final Keyword cCommaKeyword_9_1_0 = (Keyword)cGroup_9_1.eContents().get(0);
		private final Assignment cBindingsAssignment_9_1_1 = (Assignment)cGroup_9_1.eContents().get(1);
		private final RuleCall cBindingsBindingParserRuleCall_9_1_1_0 = (RuleCall)cBindingsAssignment_9_1_1.eContents().get(0);
		private final Assignment cAttachementsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cAttachementsAttachementParserRuleCall_10_0 = (RuleCall)cAttachementsAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cAttachementsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cAttachementsAttachementParserRuleCall_11_1_0 = (RuleCall)cAttachementsAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Configuration:
		//	'Configuration'
		//	name=EString
		//	'={'
		//	components+=Component ("," components+=Component)*
		//	connectors+=Connector ("," connectors+=Connector)*
		//	ports+=Port ("," ports+=Port)* (bindings+=Binding ("," bindings+=Binding)*)*
		//	attachements+=Attachement ("," attachements+=Attachement)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Configuration' name=EString '={' components+=Component ("," components+=Component)* connectors+=Connector (","
		//connectors+=Connector)* ports+=Port ("," ports+=Port)* (bindings+=Binding ("," bindings+=Binding)*)*
		//attachements+=Attachement ("," attachements+=Attachement)* '}'
		public Group getGroup() { return cGroup; }
		
		//'Configuration'
		public Keyword getConfigurationKeyword_0() { return cConfigurationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'={'
		public Keyword getEqualsSignLeftCurlyBracketKeyword_2() { return cEqualsSignLeftCurlyBracketKeyword_2; }
		
		//components+=Component
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_0() { return cComponentsComponentParserRuleCall_3_0; }
		
		//("," components+=Component)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//components+=Component
		public Assignment getComponentsAssignment_4_1() { return cComponentsAssignment_4_1; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_4_1_0() { return cComponentsComponentParserRuleCall_4_1_0; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_5() { return cConnectorsAssignment_5; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_5_0() { return cConnectorsConnectorParserRuleCall_5_0; }
		
		//("," connectors+=Connector)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_6_1() { return cConnectorsAssignment_6_1; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_6_1_0() { return cConnectorsConnectorParserRuleCall_6_1_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_7() { return cPortsAssignment_7; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_7_0() { return cPortsPortParserRuleCall_7_0; }
		
		//("," ports+=Port)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_8_1() { return cPortsAssignment_8_1; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_8_1_0() { return cPortsPortParserRuleCall_8_1_0; }
		
		//(bindings+=Binding ("," bindings+=Binding)*)*
		public Group getGroup_9() { return cGroup_9; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_9_0() { return cBindingsAssignment_9_0; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_9_0_0() { return cBindingsBindingParserRuleCall_9_0_0; }
		
		//("," bindings+=Binding)*
		public Group getGroup_9_1() { return cGroup_9_1; }
		
		//","
		public Keyword getCommaKeyword_9_1_0() { return cCommaKeyword_9_1_0; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_9_1_1() { return cBindingsAssignment_9_1_1; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_9_1_1_0() { return cBindingsBindingParserRuleCall_9_1_1_0; }
		
		//attachements+=Attachement
		public Assignment getAttachementsAssignment_10() { return cAttachementsAssignment_10; }
		
		//Attachement
		public RuleCall getAttachementsAttachementParserRuleCall_10_0() { return cAttachementsAttachementParserRuleCall_10_0; }
		
		//("," attachements+=Attachement)*
		public Group getGroup_11() { return cGroup_11; }
		
		//","
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//attachements+=Attachement
		public Assignment getAttachementsAssignment_11_1() { return cAttachementsAssignment_11_1; }
		
		//Attachement
		public RuleCall getAttachementsAttachementParserRuleCall_11_1_0() { return cAttachementsAttachementParserRuleCall_11_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class SimpleConfigurationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.SimpleConfiguration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSimpleConfigurationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cComponentsComponentParserRuleCall_3_0 = (RuleCall)cComponentsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cComponentsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cComponentsComponentParserRuleCall_4_1_0 = (RuleCall)cComponentsAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cConnectorsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cConnectorsConnectorParserRuleCall_6_0 = (RuleCall)cConnectorsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cConnectorsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cConnectorsConnectorParserRuleCall_7_1_0 = (RuleCall)cConnectorsAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cPortsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cPortsPortParserRuleCall_9_0 = (RuleCall)cPortsAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cPortsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cPortsPortParserRuleCall_10_1_0 = (RuleCall)cPortsAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Assignment cBindingsAssignment_11_0 = (Assignment)cGroup_11.eContents().get(0);
		private final RuleCall cBindingsBindingParserRuleCall_11_0_0 = (RuleCall)cBindingsAssignment_11_0.eContents().get(0);
		private final Group cGroup_11_1 = (Group)cGroup_11.eContents().get(1);
		private final Keyword cCommaKeyword_11_1_0 = (Keyword)cGroup_11_1.eContents().get(0);
		private final Assignment cBindingsAssignment_11_1_1 = (Assignment)cGroup_11_1.eContents().get(1);
		private final RuleCall cBindingsBindingParserRuleCall_11_1_1_0 = (RuleCall)cBindingsAssignment_11_1_1.eContents().get(0);
		private final Assignment cAttachementsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cAttachementsAttachementParserRuleCall_12_0 = (RuleCall)cAttachementsAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cAttachementsAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cAttachementsAttachementParserRuleCall_13_1_0 = (RuleCall)cAttachementsAssignment_13_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//SimpleConfiguration:
		//	'SimpleConfiguration'
		//	name=EString
		//	'={'
		//	components+=Component ("," components+=Component)* '}'
		//	connectors+=Connector ("," connectors+=Connector)* '}'
		//	ports+=Port ("," ports+=Port)* (bindings+=Binding ("," bindings+=Binding)*)*
		//	attachements+=Attachement ("," attachements+=Attachement)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SimpleConfiguration' name=EString '={' components+=Component ("," components+=Component)* '}' connectors+=Connector
		//("," connectors+=Connector)* '}' ports+=Port ("," ports+=Port)* (bindings+=Binding ("," bindings+=Binding)*)*
		//attachements+=Attachement ("," attachements+=Attachement)* '}'
		public Group getGroup() { return cGroup; }
		
		//'SimpleConfiguration'
		public Keyword getSimpleConfigurationKeyword_0() { return cSimpleConfigurationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'={'
		public Keyword getEqualsSignLeftCurlyBracketKeyword_2() { return cEqualsSignLeftCurlyBracketKeyword_2; }
		
		//components+=Component
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_0() { return cComponentsComponentParserRuleCall_3_0; }
		
		//("," components+=Component)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//components+=Component
		public Assignment getComponentsAssignment_4_1() { return cComponentsAssignment_4_1; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_4_1_0() { return cComponentsComponentParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_6() { return cConnectorsAssignment_6; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_6_0() { return cConnectorsConnectorParserRuleCall_6_0; }
		
		//("," connectors+=Connector)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_7_1() { return cConnectorsAssignment_7_1; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_7_1_0() { return cConnectorsConnectorParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//ports+=Port
		public Assignment getPortsAssignment_9() { return cPortsAssignment_9; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_9_0() { return cPortsPortParserRuleCall_9_0; }
		
		//("," ports+=Port)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_10_1() { return cPortsAssignment_10_1; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_10_1_0() { return cPortsPortParserRuleCall_10_1_0; }
		
		//(bindings+=Binding ("," bindings+=Binding)*)*
		public Group getGroup_11() { return cGroup_11; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_11_0() { return cBindingsAssignment_11_0; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_11_0_0() { return cBindingsBindingParserRuleCall_11_0_0; }
		
		//("," bindings+=Binding)*
		public Group getGroup_11_1() { return cGroup_11_1; }
		
		//","
		public Keyword getCommaKeyword_11_1_0() { return cCommaKeyword_11_1_0; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_11_1_1() { return cBindingsAssignment_11_1_1; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_11_1_1_0() { return cBindingsBindingParserRuleCall_11_1_1_0; }
		
		//attachements+=Attachement
		public Assignment getAttachementsAssignment_12() { return cAttachementsAssignment_12; }
		
		//Attachement
		public RuleCall getAttachementsAttachementParserRuleCall_12_0() { return cAttachementsAttachementParserRuleCall_12_0; }
		
		//("," attachements+=Attachement)*
		public Group getGroup_13() { return cGroup_13; }
		
		//","
		public Keyword getCommaKeyword_13_0() { return cCommaKeyword_13_0; }
		
		//attachements+=Attachement
		public Assignment getAttachementsAssignment_13_1() { return cAttachementsAssignment_13_1; }
		
		//Attachement
		public RuleCall getAttachementsAttachementParserRuleCall_13_1_0() { return cAttachementsAttachementParserRuleCall_13_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComponentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPortsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPortsPortParserRuleCall_3_0 = (RuleCall)cPortsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPortsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPortsPortParserRuleCall_4_1_0 = (RuleCall)cPortsAssignment_4_1.eContents().get(0);
		private final Assignment cServicesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cServicesServiceParserRuleCall_5_0 = (RuleCall)cServicesAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cServicesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cServicesServiceParserRuleCall_6_1_0 = (RuleCall)cServicesAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Component:
		//	'Component'
		//	name=EString
		//	'={'
		//	ports+=Port ("," ports+=Port)*
		//	services+=Service ("," services+=Service)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Component' name=EString '={' ports+=Port ("," ports+=Port)* services+=Service ("," services+=Service)* '}'
		public Group getGroup() { return cGroup; }
		
		//'Component'
		public Keyword getComponentKeyword_0() { return cComponentKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'={'
		public Keyword getEqualsSignLeftCurlyBracketKeyword_2() { return cEqualsSignLeftCurlyBracketKeyword_2; }
		
		//ports+=Port
		public Assignment getPortsAssignment_3() { return cPortsAssignment_3; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_3_0() { return cPortsPortParserRuleCall_3_0; }
		
		//("," ports+=Port)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_4_1() { return cPortsAssignment_4_1; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_4_1_0() { return cPortsPortParserRuleCall_4_1_0; }
		
		//services+=Service
		public Assignment getServicesAssignment_5() { return cServicesAssignment_5; }
		
		//Service
		public RuleCall getServicesServiceParserRuleCall_5_0() { return cServicesServiceParserRuleCall_5_0; }
		
		//("," services+=Service)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//services+=Service
		public Assignment getServicesAssignment_6_1() { return cServicesAssignment_6_1; }
		
		//Service
		public RuleCall getServicesServiceParserRuleCall_6_1_0() { return cServicesServiceParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ConnectorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Connector");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnectorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRolesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRolesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRolesRoleParserRuleCall_4_0 = (RuleCall)cRolesAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRolesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRolesRoleParserRuleCall_6_0 = (RuleCall)cRolesAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Connector:
		//	'Connector'
		//	name=EString
		//	'={'
		//	'Roles{' roles+=Role ',' roles+=Role '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Connector' name=EString '={' 'Roles{' roles+=Role ',' roles+=Role '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Connector'
		public Keyword getConnectorKeyword_0() { return cConnectorKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'={'
		public Keyword getEqualsSignLeftCurlyBracketKeyword_2() { return cEqualsSignLeftCurlyBracketKeyword_2; }
		
		//'Roles{'
		public Keyword getRolesKeyword_3() { return cRolesKeyword_3; }
		
		//roles+=Role
		public Assignment getRolesAssignment_4() { return cRolesAssignment_4; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_4_0() { return cRolesRoleParserRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//roles+=Role
		public Assignment getRolesAssignment_6() { return cRolesAssignment_6; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_6_0() { return cRolesRoleParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class PortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Port");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPort_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRequiredPortParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cProvidedPortParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Port:
		//	Port_Impl | RequiredPort | ProvidedPort;
		@Override public ParserRule getRule() { return rule; }
		
		//Port_Impl | RequiredPort | ProvidedPort
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Port_Impl
		public RuleCall getPort_ImplParserRuleCall_0() { return cPort_ImplParserRuleCall_0; }
		
		//RequiredPort
		public RuleCall getRequiredPortParserRuleCall_1() { return cRequiredPortParserRuleCall_1; }
		
		//ProvidedPort
		public RuleCall getProvidedPortParserRuleCall_2() { return cProvidedPortParserRuleCall_2; }
	}
	public class ServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Service");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cService_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRequiredServiceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cProvidedServiceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Service:
		//	Service_Impl | RequiredService | ProvidedService;
		@Override public ParserRule getRule() { return rule; }
		
		//Service_Impl | RequiredService | ProvidedService
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Service_Impl
		public RuleCall getService_ImplParserRuleCall_0() { return cService_ImplParserRuleCall_0; }
		
		//RequiredService
		public RuleCall getRequiredServiceParserRuleCall_1() { return cRequiredServiceParserRuleCall_1; }
		
		//ProvidedService
		public RuleCall getProvidedServiceParserRuleCall_2() { return cProvidedServiceParserRuleCall_2; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Role");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRole_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRequiredRoleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cProvidedRoleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Role:
		//	Role_Impl | RequiredRole | ProvidedRole;
		@Override public ParserRule getRule() { return rule; }
		
		//Role_Impl | RequiredRole | ProvidedRole
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Role_Impl
		public RuleCall getRole_ImplParserRuleCall_0() { return cRole_ImplParserRuleCall_0; }
		
		//RequiredRole
		public RuleCall getRequiredRoleParserRuleCall_1() { return cRequiredRoleParserRuleCall_1; }
		
		//ProvidedRole
		public RuleCall getProvidedRoleParserRuleCall_2() { return cProvidedRoleParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class Port_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Port_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPortAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Port_Impl Port:
		//	{Port}
		//	'Port'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Port} 'Port' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Port}
		public Action getPortAction_0() { return cPortAction_0; }
		
		//'Port'
		public Keyword getPortKeyword_1() { return cPortKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class BindingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Binding");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBindingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPortProvidedAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPortProvidedPortParserRuleCall_2_0 = (RuleCall)cPortProvidedAssignment_2.eContents().get(0);
		private final Assignment cPortRequiredAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPortRequiredPortParserRuleCall_3_0 = (RuleCall)cPortRequiredAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Binding:
		//	'Binding'
		//	'{'
		//	portProvided=Port
		//	portRequired=Port
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Binding' '{' portProvided=Port portRequired=Port '}'
		public Group getGroup() { return cGroup; }
		
		//'Binding'
		public Keyword getBindingKeyword_0() { return cBindingKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//portProvided=Port
		public Assignment getPortProvidedAssignment_2() { return cPortProvidedAssignment_2; }
		
		//Port
		public RuleCall getPortProvidedPortParserRuleCall_2_0() { return cPortProvidedPortParserRuleCall_2_0; }
		
		//portRequired=Port
		public Assignment getPortRequiredAssignment_3() { return cPortRequiredAssignment_3; }
		
		//Port
		public RuleCall getPortRequiredPortParserRuleCall_3_0() { return cPortRequiredPortParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class AttachementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Attachement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAttachementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRoleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRoleRoleParserRuleCall_2_0 = (RuleCall)cRoleAssignment_2.eContents().get(0);
		private final Keyword cToKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPortAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPortPortParserRuleCall_4_0 = (RuleCall)cPortAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Attachement:
		//	'Attachement'
		//	':{'
		//	role=Role "to" port=Port
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Attachement' ':{' role=Role "to" port=Port '}'
		public Group getGroup() { return cGroup; }
		
		//'Attachement'
		public Keyword getAttachementKeyword_0() { return cAttachementKeyword_0; }
		
		//':{'
		public Keyword getColonLeftCurlyBracketKeyword_1() { return cColonLeftCurlyBracketKeyword_1; }
		
		//role=Role
		public Assignment getRoleAssignment_2() { return cRoleAssignment_2; }
		
		//Role
		public RuleCall getRoleRoleParserRuleCall_2_0() { return cRoleRoleParserRuleCall_2_0; }
		
		//"to"
		public Keyword getToKeyword_3() { return cToKeyword_3; }
		
		//port=Port
		public Assignment getPortAssignment_4() { return cPortAssignment_4; }
		
		//Port
		public RuleCall getPortPortParserRuleCall_4_0() { return cPortPortParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class Service_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Service_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cServiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Service_Impl Service:
		//	{Service}
		//	'Service'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Service} 'Service' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Service}
		public Action getServiceAction_0() { return cServiceAction_0; }
		
		//'Service'
		public Keyword getServiceKeyword_1() { return cServiceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class RequiredServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.RequiredService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequiredServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRequiredServiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//RequiredService:
		//	{RequiredService}
		//	'RequiredService'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{RequiredService} 'RequiredService' name=EString
		public Group getGroup() { return cGroup; }
		
		//{RequiredService}
		public Action getRequiredServiceAction_0() { return cRequiredServiceAction_0; }
		
		//'RequiredService'
		public Keyword getRequiredServiceKeyword_1() { return cRequiredServiceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ProvidedServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.ProvidedService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProvidedServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProvidedServiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//ProvidedService:
		//	{ProvidedService}
		//	'ProvidedService'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{ProvidedService} 'ProvidedService' name=EString
		public Group getGroup() { return cGroup; }
		
		//{ProvidedService}
		public Action getProvidedServiceAction_0() { return cProvidedServiceAction_0; }
		
		//'ProvidedService'
		public Keyword getProvidedServiceKeyword_1() { return cProvidedServiceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class Role_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Role_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRoleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Role_Impl Role:
		//	{Role}
		//	'Role'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Role} 'Role' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Role}
		public Action getRoleAction_0() { return cRoleAction_0; }
		
		//'Role'
		public Keyword getRoleKeyword_1() { return cRoleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class RequiredRoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.RequiredRole");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequiredRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRequiredRoleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//RequiredRole:
		//	{RequiredRole}
		//	'RequiredRole'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{RequiredRole} 'RequiredRole' name=EString
		public Group getGroup() { return cGroup; }
		
		//{RequiredRole}
		public Action getRequiredRoleAction_0() { return cRequiredRoleAction_0; }
		
		//'RequiredRole'
		public Keyword getRequiredRoleKeyword_1() { return cRequiredRoleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ProvidedRoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.ProvidedRole");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProvidedRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProvidedRoleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//ProvidedRole:
		//	{ProvidedRole}
		//	'ProvidedRole'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{ProvidedRole} 'ProvidedRole' name=EString
		public Group getGroup() { return cGroup; }
		
		//{ProvidedRole}
		public Action getProvidedRoleAction_0() { return cProvidedRoleAction_0; }
		
		//'ProvidedRole'
		public Keyword getProvidedRoleKeyword_1() { return cProvidedRoleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class RequiredPortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.RequiredPort");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequiredPortAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRequiredPortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//RequiredPort:
		//	{RequiredPort}
		//	'RequiredPort'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{RequiredPort} 'RequiredPort' name=EString
		public Group getGroup() { return cGroup; }
		
		//{RequiredPort}
		public Action getRequiredPortAction_0() { return cRequiredPortAction_0; }
		
		//'RequiredPort'
		public Keyword getRequiredPortKeyword_1() { return cRequiredPortKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ProvidedPortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.ProvidedPort");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProvidedPortAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProvidedPortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//ProvidedPort:
		//	{ProvidedPort}
		//	'ProvidedPort'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{ProvidedPort} 'ProvidedPort' name=EString
		public Group getGroup() { return cGroup; }
		
		//{ProvidedPort}
		public Action getProvidedPortAction_0() { return cProvidedPortAction_0; }
		
		//'ProvidedPort'
		public Keyword getProvidedPortKeyword_1() { return cProvidedPortKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	
	
	private final CompositeConfigurationElements pCompositeConfiguration;
	private final ConfigurationElements pConfiguration;
	private final SimpleConfigurationElements pSimpleConfiguration;
	private final ComponentElements pComponent;
	private final ConnectorElements pConnector;
	private final PortElements pPort;
	private final ServiceElements pService;
	private final RoleElements pRole;
	private final EStringElements pEString;
	private final Port_ImplElements pPort_Impl;
	private final BindingElements pBinding;
	private final AttachementElements pAttachement;
	private final Service_ImplElements pService_Impl;
	private final RequiredServiceElements pRequiredService;
	private final ProvidedServiceElements pProvidedService;
	private final Role_ImplElements pRole_Impl;
	private final RequiredRoleElements pRequiredRole;
	private final ProvidedRoleElements pProvidedRole;
	private final RequiredPortElements pRequiredPort;
	private final ProvidedPortElements pProvidedPort;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CosaDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCompositeConfiguration = new CompositeConfigurationElements();
		this.pConfiguration = new ConfigurationElements();
		this.pSimpleConfiguration = new SimpleConfigurationElements();
		this.pComponent = new ComponentElements();
		this.pConnector = new ConnectorElements();
		this.pPort = new PortElements();
		this.pService = new ServiceElements();
		this.pRole = new RoleElements();
		this.pEString = new EStringElements();
		this.pPort_Impl = new Port_ImplElements();
		this.pBinding = new BindingElements();
		this.pAttachement = new AttachementElements();
		this.pService_Impl = new Service_ImplElements();
		this.pRequiredService = new RequiredServiceElements();
		this.pProvidedService = new ProvidedServiceElements();
		this.pRole_Impl = new Role_ImplElements();
		this.pRequiredRole = new RequiredRoleElements();
		this.pProvidedRole = new ProvidedRoleElements();
		this.pRequiredPort = new RequiredPortElements();
		this.pProvidedPort = new ProvidedPortElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.univnantes.asa.xtext.CosaDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//CompositeConfiguration:
	//	'CompositeConfiguration'
	//	name=EString
	//	'={'
	//	components+=Component ("," components+=Component)*
	//	connectors+=Connector ("," connectors+=Connector)*
	//	ports+=Port ("," ports+=Port)* (bindings+=Binding ("," bindings+=Binding)*)*
	//	attachements+=Attachement ("," attachements+=Attachement)* (configurations+=Configuration (","
	//	configurations+=Configuration)*)*
	//	'}';
	public CompositeConfigurationElements getCompositeConfigurationAccess() {
		return pCompositeConfiguration;
	}
	
	public ParserRule getCompositeConfigurationRule() {
		return getCompositeConfigurationAccess().getRule();
	}
	
	//Configuration:
	//	'Configuration'
	//	name=EString
	//	'={'
	//	components+=Component ("," components+=Component)*
	//	connectors+=Connector ("," connectors+=Connector)*
	//	ports+=Port ("," ports+=Port)* (bindings+=Binding ("," bindings+=Binding)*)*
	//	attachements+=Attachement ("," attachements+=Attachement)*
	//	'}';
	public ConfigurationElements getConfigurationAccess() {
		return pConfiguration;
	}
	
	public ParserRule getConfigurationRule() {
		return getConfigurationAccess().getRule();
	}
	
	//SimpleConfiguration:
	//	'SimpleConfiguration'
	//	name=EString
	//	'={'
	//	components+=Component ("," components+=Component)* '}'
	//	connectors+=Connector ("," connectors+=Connector)* '}'
	//	ports+=Port ("," ports+=Port)* (bindings+=Binding ("," bindings+=Binding)*)*
	//	attachements+=Attachement ("," attachements+=Attachement)*
	//	'}';
	public SimpleConfigurationElements getSimpleConfigurationAccess() {
		return pSimpleConfiguration;
	}
	
	public ParserRule getSimpleConfigurationRule() {
		return getSimpleConfigurationAccess().getRule();
	}
	
	//Component:
	//	'Component'
	//	name=EString
	//	'={'
	//	ports+=Port ("," ports+=Port)*
	//	services+=Service ("," services+=Service)*
	//	'}';
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//Connector:
	//	'Connector'
	//	name=EString
	//	'={'
	//	'Roles{' roles+=Role ',' roles+=Role '}'
	//	'}';
	public ConnectorElements getConnectorAccess() {
		return pConnector;
	}
	
	public ParserRule getConnectorRule() {
		return getConnectorAccess().getRule();
	}
	
	//Port:
	//	Port_Impl | RequiredPort | ProvidedPort;
	public PortElements getPortAccess() {
		return pPort;
	}
	
	public ParserRule getPortRule() {
		return getPortAccess().getRule();
	}
	
	//Service:
	//	Service_Impl | RequiredService | ProvidedService;
	public ServiceElements getServiceAccess() {
		return pService;
	}
	
	public ParserRule getServiceRule() {
		return getServiceAccess().getRule();
	}
	
	//Role:
	//	Role_Impl | RequiredRole | ProvidedRole;
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Port_Impl Port:
	//	{Port}
	//	'Port'
	//	name=EString;
	public Port_ImplElements getPort_ImplAccess() {
		return pPort_Impl;
	}
	
	public ParserRule getPort_ImplRule() {
		return getPort_ImplAccess().getRule();
	}
	
	//Binding:
	//	'Binding'
	//	'{'
	//	portProvided=Port
	//	portRequired=Port
	//	'}';
	public BindingElements getBindingAccess() {
		return pBinding;
	}
	
	public ParserRule getBindingRule() {
		return getBindingAccess().getRule();
	}
	
	//Attachement:
	//	'Attachement'
	//	':{'
	//	role=Role "to" port=Port
	//	'}';
	public AttachementElements getAttachementAccess() {
		return pAttachement;
	}
	
	public ParserRule getAttachementRule() {
		return getAttachementAccess().getRule();
	}
	
	//Service_Impl Service:
	//	{Service}
	//	'Service'
	//	name=EString;
	public Service_ImplElements getService_ImplAccess() {
		return pService_Impl;
	}
	
	public ParserRule getService_ImplRule() {
		return getService_ImplAccess().getRule();
	}
	
	//RequiredService:
	//	{RequiredService}
	//	'RequiredService'
	//	name=EString;
	public RequiredServiceElements getRequiredServiceAccess() {
		return pRequiredService;
	}
	
	public ParserRule getRequiredServiceRule() {
		return getRequiredServiceAccess().getRule();
	}
	
	//ProvidedService:
	//	{ProvidedService}
	//	'ProvidedService'
	//	name=EString;
	public ProvidedServiceElements getProvidedServiceAccess() {
		return pProvidedService;
	}
	
	public ParserRule getProvidedServiceRule() {
		return getProvidedServiceAccess().getRule();
	}
	
	//Role_Impl Role:
	//	{Role}
	//	'Role'
	//	name=EString;
	public Role_ImplElements getRole_ImplAccess() {
		return pRole_Impl;
	}
	
	public ParserRule getRole_ImplRule() {
		return getRole_ImplAccess().getRule();
	}
	
	//RequiredRole:
	//	{RequiredRole}
	//	'RequiredRole'
	//	name=EString;
	public RequiredRoleElements getRequiredRoleAccess() {
		return pRequiredRole;
	}
	
	public ParserRule getRequiredRoleRule() {
		return getRequiredRoleAccess().getRule();
	}
	
	//ProvidedRole:
	//	{ProvidedRole}
	//	'ProvidedRole'
	//	name=EString;
	public ProvidedRoleElements getProvidedRoleAccess() {
		return pProvidedRole;
	}
	
	public ParserRule getProvidedRoleRule() {
		return getProvidedRoleAccess().getRule();
	}
	
	//RequiredPort:
	//	{RequiredPort}
	//	'RequiredPort'
	//	name=EString;
	public RequiredPortElements getRequiredPortAccess() {
		return pRequiredPort;
	}
	
	public ParserRule getRequiredPortRule() {
		return getRequiredPortAccess().getRule();
	}
	
	//ProvidedPort:
	//	{ProvidedPort}
	//	'ProvidedPort'
	//	name=EString;
	public ProvidedPortElements getProvidedPortAccess() {
		return pProvidedPort;
	}
	
	public ParserRule getProvidedPortRule() {
		return getProvidedPortAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
