/*
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CosaDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ConfigurationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Configuration");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cConfiguration_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSimpleConfigurationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCompositeConfigurationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Configuration:
		//	Configuration_Impl | SimpleConfiguration | CompositeConfiguration;
		@Override public ParserRule getRule() { return rule; }
		
		//Configuration_Impl | SimpleConfiguration | CompositeConfiguration
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Configuration_Impl
		public RuleCall getConfiguration_ImplParserRuleCall_0() { return cConfiguration_ImplParserRuleCall_0; }
		
		//SimpleConfiguration
		public RuleCall getSimpleConfigurationParserRuleCall_1() { return cSimpleConfigurationParserRuleCall_1; }
		
		//CompositeConfiguration
		public RuleCall getCompositeConfigurationParserRuleCall_2() { return cCompositeConfigurationParserRuleCall_2; }
	}
	public class PortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Port");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPort_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRequiredPortParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cProvidedPortParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Port:
		//	Port_Impl | RequiredPort | ProvidedPort;
		@Override public ParserRule getRule() { return rule; }
		
		//Port_Impl | RequiredPort | ProvidedPort
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Port_Impl
		public RuleCall getPort_ImplParserRuleCall_0() { return cPort_ImplParserRuleCall_0; }
		
		//RequiredPort
		public RuleCall getRequiredPortParserRuleCall_1() { return cRequiredPortParserRuleCall_1; }
		
		//ProvidedPort
		public RuleCall getProvidedPortParserRuleCall_2() { return cProvidedPortParserRuleCall_2; }
	}
	public class ServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Service");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cService_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRequiredServiceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cProvidedServiceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Service:
		//	Service_Impl | RequiredService | ProvidedService;
		@Override public ParserRule getRule() { return rule; }
		
		//Service_Impl | RequiredService | ProvidedService
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Service_Impl
		public RuleCall getService_ImplParserRuleCall_0() { return cService_ImplParserRuleCall_0; }
		
		//RequiredService
		public RuleCall getRequiredServiceParserRuleCall_1() { return cRequiredServiceParserRuleCall_1; }
		
		//ProvidedService
		public RuleCall getProvidedServiceParserRuleCall_2() { return cProvidedServiceParserRuleCall_2; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Role");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRole_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRequiredRoleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cProvidedRoleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Role:
		//	Role_Impl | RequiredRole | ProvidedRole;
		@Override public ParserRule getRule() { return rule; }
		
		//Role_Impl | RequiredRole | ProvidedRole
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Role_Impl
		public RuleCall getRole_ImplParserRuleCall_0() { return cRole_ImplParserRuleCall_0; }
		
		//RequiredRole
		public RuleCall getRequiredRoleParserRuleCall_1() { return cRequiredRoleParserRuleCall_1; }
		
		//ProvidedRole
		public RuleCall getProvidedRoleParserRuleCall_2() { return cProvidedRoleParserRuleCall_2; }
	}
	public class CompositeConfigurationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.CompositeConfiguration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompositeConfigurationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cComponentsAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cComponentsComponentParserRuleCall_3_0_0 = (RuleCall)cComponentsAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cComponentsAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cComponentsComponentParserRuleCall_3_1_1_0 = (RuleCall)cComponentsAssignment_3_1_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cConnectorsAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cConnectorsConnectorParserRuleCall_4_0_0 = (RuleCall)cConnectorsAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cConnectorsAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cConnectorsConnectorParserRuleCall_4_1_1_0 = (RuleCall)cConnectorsAssignment_4_1_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cPortsAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cPortsPortParserRuleCall_5_0_0 = (RuleCall)cPortsAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cCommaKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cPortsAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cPortsPortParserRuleCall_5_1_1_0 = (RuleCall)cPortsAssignment_5_1_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cBindingsAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cBindingsBindingParserRuleCall_6_0_0 = (RuleCall)cBindingsAssignment_6_0.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Keyword cCommaKeyword_6_1_0 = (Keyword)cGroup_6_1.eContents().get(0);
		private final Assignment cBindingsAssignment_6_1_1 = (Assignment)cGroup_6_1.eContents().get(1);
		private final RuleCall cBindingsBindingParserRuleCall_6_1_1_0 = (RuleCall)cBindingsAssignment_6_1_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cAttachementsAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cAttachementsAttachementParserRuleCall_7_0_0 = (RuleCall)cAttachementsAssignment_7_0.eContents().get(0);
		private final Group cGroup_7_1 = (Group)cGroup_7.eContents().get(1);
		private final Keyword cCommaKeyword_7_1_0 = (Keyword)cGroup_7_1.eContents().get(0);
		private final Assignment cAttachementsAssignment_7_1_1 = (Assignment)cGroup_7_1.eContents().get(1);
		private final RuleCall cAttachementsAttachementParserRuleCall_7_1_1_0 = (RuleCall)cAttachementsAssignment_7_1_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Assignment cConfigurationsAssignment_8_0 = (Assignment)cGroup_8.eContents().get(0);
		private final RuleCall cConfigurationsConfigurationParserRuleCall_8_0_0 = (RuleCall)cConfigurationsAssignment_8_0.eContents().get(0);
		private final Group cGroup_8_1 = (Group)cGroup_8.eContents().get(1);
		private final Keyword cCommaKeyword_8_1_0 = (Keyword)cGroup_8_1.eContents().get(0);
		private final Assignment cConfigurationsAssignment_8_1_1 = (Assignment)cGroup_8_1.eContents().get(1);
		private final RuleCall cConfigurationsConfigurationParserRuleCall_8_1_1_0 = (RuleCall)cConfigurationsAssignment_8_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//CompositeConfiguration:
		//	'CompositeConfiguration'
		//	name=EString
		//	'{' (components+=Component ("," components+=Component)*) (connectors+=Connector ("," connectors+=Connector)*)*
		//	(ports+=Port ("," ports+=Port)*)* (bindings+=Binding ("," bindings+=Binding)*)* (attachements+=Attachement (","
		//	attachements+=Attachement)*)* (configurations+=Configuration ("," configurations+=Configuration)*)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'CompositeConfiguration' name=EString '{' (components+=Component ("," components+=Component)*) (connectors+=Connector
		//("," connectors+=Connector)*)* (ports+=Port ("," ports+=Port)*)* (bindings+=Binding ("," bindings+=Binding)*)*
		//(attachements+=Attachement ("," attachements+=Attachement)*)* (configurations+=Configuration (","
		//configurations+=Configuration)*)* '}'
		public Group getGroup() { return cGroup; }
		
		//'CompositeConfiguration'
		public Keyword getCompositeConfigurationKeyword_0() { return cCompositeConfigurationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//components+=Component ("," components+=Component)*
		public Group getGroup_3() { return cGroup_3; }
		
		//components+=Component
		public Assignment getComponentsAssignment_3_0() { return cComponentsAssignment_3_0; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_0_0() { return cComponentsComponentParserRuleCall_3_0_0; }
		
		//("," components+=Component)*
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }
		
		//components+=Component
		public Assignment getComponentsAssignment_3_1_1() { return cComponentsAssignment_3_1_1; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_1_1_0() { return cComponentsComponentParserRuleCall_3_1_1_0; }
		
		//(connectors+=Connector ("," connectors+=Connector)*)*
		public Group getGroup_4() { return cGroup_4; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_4_0() { return cConnectorsAssignment_4_0; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_4_0_0() { return cConnectorsConnectorParserRuleCall_4_0_0; }
		
		//("," connectors+=Connector)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_4_1_1() { return cConnectorsAssignment_4_1_1; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_4_1_1_0() { return cConnectorsConnectorParserRuleCall_4_1_1_0; }
		
		//(ports+=Port ("," ports+=Port)*)*
		public Group getGroup_5() { return cGroup_5; }
		
		//ports+=Port
		public Assignment getPortsAssignment_5_0() { return cPortsAssignment_5_0; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_5_0_0() { return cPortsPortParserRuleCall_5_0_0; }
		
		//("," ports+=Port)*
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//","
		public Keyword getCommaKeyword_5_1_0() { return cCommaKeyword_5_1_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_5_1_1() { return cPortsAssignment_5_1_1; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_5_1_1_0() { return cPortsPortParserRuleCall_5_1_1_0; }
		
		//(bindings+=Binding ("," bindings+=Binding)*)*
		public Group getGroup_6() { return cGroup_6; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_6_0() { return cBindingsAssignment_6_0; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_6_0_0() { return cBindingsBindingParserRuleCall_6_0_0; }
		
		//("," bindings+=Binding)*
		public Group getGroup_6_1() { return cGroup_6_1; }
		
		//","
		public Keyword getCommaKeyword_6_1_0() { return cCommaKeyword_6_1_0; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_6_1_1() { return cBindingsAssignment_6_1_1; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_6_1_1_0() { return cBindingsBindingParserRuleCall_6_1_1_0; }
		
		//(attachements+=Attachement ("," attachements+=Attachement)*)*
		public Group getGroup_7() { return cGroup_7; }
		
		//attachements+=Attachement
		public Assignment getAttachementsAssignment_7_0() { return cAttachementsAssignment_7_0; }
		
		//Attachement
		public RuleCall getAttachementsAttachementParserRuleCall_7_0_0() { return cAttachementsAttachementParserRuleCall_7_0_0; }
		
		//("," attachements+=Attachement)*
		public Group getGroup_7_1() { return cGroup_7_1; }
		
		//","
		public Keyword getCommaKeyword_7_1_0() { return cCommaKeyword_7_1_0; }
		
		//attachements+=Attachement
		public Assignment getAttachementsAssignment_7_1_1() { return cAttachementsAssignment_7_1_1; }
		
		//Attachement
		public RuleCall getAttachementsAttachementParserRuleCall_7_1_1_0() { return cAttachementsAttachementParserRuleCall_7_1_1_0; }
		
		//(configurations+=Configuration ("," configurations+=Configuration)*)*
		public Group getGroup_8() { return cGroup_8; }
		
		//configurations+=Configuration
		public Assignment getConfigurationsAssignment_8_0() { return cConfigurationsAssignment_8_0; }
		
		//Configuration
		public RuleCall getConfigurationsConfigurationParserRuleCall_8_0_0() { return cConfigurationsConfigurationParserRuleCall_8_0_0; }
		
		//("," configurations+=Configuration)*
		public Group getGroup_8_1() { return cGroup_8_1; }
		
		//","
		public Keyword getCommaKeyword_8_1_0() { return cCommaKeyword_8_1_0; }
		
		//configurations+=Configuration
		public Assignment getConfigurationsAssignment_8_1_1() { return cConfigurationsAssignment_8_1_1; }
		
		//Configuration
		public RuleCall getConfigurationsConfigurationParserRuleCall_8_1_1_0() { return cConfigurationsConfigurationParserRuleCall_8_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComponentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPortsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPortsPortParserRuleCall_3_0 = (RuleCall)cPortsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPortsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPortsPortParserRuleCall_4_1_0 = (RuleCall)cPortsAssignment_4_1.eContents().get(0);
		private final Assignment cServicesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cServicesServiceParserRuleCall_5_0 = (RuleCall)cServicesAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cServicesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cServicesServiceParserRuleCall_6_1_0 = (RuleCall)cServicesAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Component:
		//	'Component'
		//	name=EString
		//	'{'
		//	ports+=Port ("," ports+=Port)*
		//	services+=Service ("," services+=Service)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Component' name=EString '{' ports+=Port ("," ports+=Port)* services+=Service ("," services+=Service)* '}'
		public Group getGroup() { return cGroup; }
		
		//'Component'
		public Keyword getComponentKeyword_0() { return cComponentKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//ports+=Port
		public Assignment getPortsAssignment_3() { return cPortsAssignment_3; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_3_0() { return cPortsPortParserRuleCall_3_0; }
		
		//("," ports+=Port)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_4_1() { return cPortsAssignment_4_1; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_4_1_0() { return cPortsPortParserRuleCall_4_1_0; }
		
		//services+=Service
		public Assignment getServicesAssignment_5() { return cServicesAssignment_5; }
		
		//Service
		public RuleCall getServicesServiceParserRuleCall_5_0() { return cServicesServiceParserRuleCall_5_0; }
		
		//("," services+=Service)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//services+=Service
		public Assignment getServicesAssignment_6_1() { return cServicesAssignment_6_1; }
		
		//Service
		public RuleCall getServicesServiceParserRuleCall_6_1_0() { return cServicesServiceParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ConnectorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Connector");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnectorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRolesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRolesRoleParserRuleCall_3_0 = (RuleCall)cRolesAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRolesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRolesRoleParserRuleCall_4_1_0 = (RuleCall)cRolesAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cGlueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cGlueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cGlueGlueParserRuleCall_5_1_0 = (RuleCall)cGlueAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Connector:
		//	'Connector'
		//	name=EString
		//	'{'
		//	roles+=Role ("," roles+=Role)* ('glue' glue=Glue)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Connector' name=EString '{' roles+=Role ("," roles+=Role)* ('glue' glue=Glue)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Connector'
		public Keyword getConnectorKeyword_0() { return cConnectorKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//roles+=Role
		public Assignment getRolesAssignment_3() { return cRolesAssignment_3; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_3_0() { return cRolesRoleParserRuleCall_3_0; }
		
		//("," roles+=Role)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//roles+=Role
		public Assignment getRolesAssignment_4_1() { return cRolesAssignment_4_1; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_4_1_0() { return cRolesRoleParserRuleCall_4_1_0; }
		
		//('glue' glue=Glue)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'glue'
		public Keyword getGlueKeyword_5_0() { return cGlueKeyword_5_0; }
		
		//glue=Glue
		public Assignment getGlueAssignment_5_1() { return cGlueAssignment_5_1; }
		
		//Glue
		public RuleCall getGlueGlueParserRuleCall_5_1_0() { return cGlueGlueParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class Port_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Port_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPortAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Port_Impl Port:
		//	{Port}
		//	'Port'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Port} 'Port' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Port}
		public Action getPortAction_0() { return cPortAction_0; }
		
		//'Port'
		public Keyword getPortKeyword_1() { return cPortKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class BindingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Binding");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBindingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConfigurationProviderAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cConfigurationProviderConfigurationCrossReference_2_0 = (CrossReference)cConfigurationProviderAssignment_2.eContents().get(0);
		private final RuleCall cConfigurationProviderConfigurationIDTerminalRuleCall_2_0_1 = (RuleCall)cConfigurationProviderConfigurationCrossReference_2_0.eContents().get(1);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPortProvidedAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cPortProvidedPortCrossReference_4_0 = (CrossReference)cPortProvidedAssignment_4.eContents().get(0);
		private final RuleCall cPortProvidedPortIDTerminalRuleCall_4_0_1 = (RuleCall)cPortProvidedPortCrossReference_4_0.eContents().get(1);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cComponentSubscriberAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cComponentSubscriberComponentCrossReference_6_0 = (CrossReference)cComponentSubscriberAssignment_6.eContents().get(0);
		private final RuleCall cComponentSubscriberComponentIDTerminalRuleCall_6_0_1 = (RuleCall)cComponentSubscriberComponentCrossReference_6_0.eContents().get(1);
		private final Keyword cFullStopKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cPortRequiredAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cPortRequiredPortCrossReference_8_0 = (CrossReference)cPortRequiredAssignment_8.eContents().get(0);
		private final RuleCall cPortRequiredPortIDTerminalRuleCall_8_0_1 = (RuleCall)cPortRequiredPortCrossReference_8_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Binding:
		//	'Binding'
		//	'('
		//	configurationProvider=[Configuration] '.' portProvided=[Port] ',' componentSubscriber=[Component] '.'
		//	portRequired=[Port]
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//'Binding' '(' configurationProvider=[Configuration] '.' portProvided=[Port] ',' componentSubscriber=[Component] '.'
		//portRequired=[Port] ')'
		public Group getGroup() { return cGroup; }
		
		//'Binding'
		public Keyword getBindingKeyword_0() { return cBindingKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//configurationProvider=[Configuration]
		public Assignment getConfigurationProviderAssignment_2() { return cConfigurationProviderAssignment_2; }
		
		//[Configuration]
		public CrossReference getConfigurationProviderConfigurationCrossReference_2_0() { return cConfigurationProviderConfigurationCrossReference_2_0; }
		
		//ID
		public RuleCall getConfigurationProviderConfigurationIDTerminalRuleCall_2_0_1() { return cConfigurationProviderConfigurationIDTerminalRuleCall_2_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
		
		//portProvided=[Port]
		public Assignment getPortProvidedAssignment_4() { return cPortProvidedAssignment_4; }
		
		//[Port]
		public CrossReference getPortProvidedPortCrossReference_4_0() { return cPortProvidedPortCrossReference_4_0; }
		
		//ID
		public RuleCall getPortProvidedPortIDTerminalRuleCall_4_0_1() { return cPortProvidedPortIDTerminalRuleCall_4_0_1; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//componentSubscriber=[Component]
		public Assignment getComponentSubscriberAssignment_6() { return cComponentSubscriberAssignment_6; }
		
		//[Component]
		public CrossReference getComponentSubscriberComponentCrossReference_6_0() { return cComponentSubscriberComponentCrossReference_6_0; }
		
		//ID
		public RuleCall getComponentSubscriberComponentIDTerminalRuleCall_6_0_1() { return cComponentSubscriberComponentIDTerminalRuleCall_6_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_7() { return cFullStopKeyword_7; }
		
		//portRequired=[Port]
		public Assignment getPortRequiredAssignment_8() { return cPortRequiredAssignment_8; }
		
		//[Port]
		public CrossReference getPortRequiredPortCrossReference_8_0() { return cPortRequiredPortCrossReference_8_0; }
		
		//ID
		public RuleCall getPortRequiredPortIDTerminalRuleCall_8_0_1() { return cPortRequiredPortIDTerminalRuleCall_8_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
	}
	public class AttachementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Attachement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAttachementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cComponentAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cComponentComponentCrossReference_2_0 = (CrossReference)cComponentAssignment_2.eContents().get(0);
		private final RuleCall cComponentComponentIDTerminalRuleCall_2_0_1 = (RuleCall)cComponentComponentCrossReference_2_0.eContents().get(1);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPortAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cPortPortCrossReference_4_0 = (CrossReference)cPortAssignment_4.eContents().get(0);
		private final RuleCall cPortPortIDTerminalRuleCall_4_0_1 = (RuleCall)cPortPortCrossReference_4_0.eContents().get(1);
		private final Keyword cToKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cConnectorAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cConnectorConnectorCrossReference_6_0 = (CrossReference)cConnectorAssignment_6.eContents().get(0);
		private final RuleCall cConnectorConnectorIDTerminalRuleCall_6_0_1 = (RuleCall)cConnectorConnectorCrossReference_6_0.eContents().get(1);
		private final Keyword cFullStopKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cRoleAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cRoleRoleCrossReference_8_0 = (CrossReference)cRoleAssignment_8.eContents().get(0);
		private final RuleCall cRoleRoleIDTerminalRuleCall_8_0_1 = (RuleCall)cRoleRoleCrossReference_8_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Attachement:
		//	'Attachement'
		//	'{'
		//	component=[Component] '.' port=[Port] 'to' connector=[Connector] '.' role=[Role]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Attachement' '{' component=[Component] '.' port=[Port] 'to' connector=[Connector] '.' role=[Role] '}'
		public Group getGroup() { return cGroup; }
		
		//'Attachement'
		public Keyword getAttachementKeyword_0() { return cAttachementKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//component=[Component]
		public Assignment getComponentAssignment_2() { return cComponentAssignment_2; }
		
		//[Component]
		public CrossReference getComponentComponentCrossReference_2_0() { return cComponentComponentCrossReference_2_0; }
		
		//ID
		public RuleCall getComponentComponentIDTerminalRuleCall_2_0_1() { return cComponentComponentIDTerminalRuleCall_2_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
		
		//port=[Port]
		public Assignment getPortAssignment_4() { return cPortAssignment_4; }
		
		//[Port]
		public CrossReference getPortPortCrossReference_4_0() { return cPortPortCrossReference_4_0; }
		
		//ID
		public RuleCall getPortPortIDTerminalRuleCall_4_0_1() { return cPortPortIDTerminalRuleCall_4_0_1; }
		
		//'to'
		public Keyword getToKeyword_5() { return cToKeyword_5; }
		
		//connector=[Connector]
		public Assignment getConnectorAssignment_6() { return cConnectorAssignment_6; }
		
		//[Connector]
		public CrossReference getConnectorConnectorCrossReference_6_0() { return cConnectorConnectorCrossReference_6_0; }
		
		//ID
		public RuleCall getConnectorConnectorIDTerminalRuleCall_6_0_1() { return cConnectorConnectorIDTerminalRuleCall_6_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_7() { return cFullStopKeyword_7; }
		
		//role=[Role]
		public Assignment getRoleAssignment_8() { return cRoleAssignment_8; }
		
		//[Role]
		public CrossReference getRoleRoleCrossReference_8_0() { return cRoleRoleCrossReference_8_0; }
		
		//ID
		public RuleCall getRoleRoleIDTerminalRuleCall_8_0_1() { return cRoleRoleIDTerminalRuleCall_8_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class Configuration_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Configuration_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConfigurationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cComponentsComponentParserRuleCall_3_0 = (RuleCall)cComponentsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cComponentsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cComponentsComponentParserRuleCall_4_1_0 = (RuleCall)cComponentsAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cConnectorsAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cConnectorsConnectorParserRuleCall_5_0_0 = (RuleCall)cConnectorsAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cCommaKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cConnectorsAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cConnectorsConnectorParserRuleCall_5_1_1_0 = (RuleCall)cConnectorsAssignment_5_1_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cPortsAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cPortsPortParserRuleCall_6_0_0 = (RuleCall)cPortsAssignment_6_0.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Keyword cCommaKeyword_6_1_0 = (Keyword)cGroup_6_1.eContents().get(0);
		private final Assignment cPortsAssignment_6_1_1 = (Assignment)cGroup_6_1.eContents().get(1);
		private final RuleCall cPortsPortParserRuleCall_6_1_1_0 = (RuleCall)cPortsAssignment_6_1_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cBindingsAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cBindingsBindingParserRuleCall_7_0_0 = (RuleCall)cBindingsAssignment_7_0.eContents().get(0);
		private final Group cGroup_7_1 = (Group)cGroup_7.eContents().get(1);
		private final Keyword cCommaKeyword_7_1_0 = (Keyword)cGroup_7_1.eContents().get(0);
		private final Assignment cBindingsAssignment_7_1_1 = (Assignment)cGroup_7_1.eContents().get(1);
		private final RuleCall cBindingsBindingParserRuleCall_7_1_1_0 = (RuleCall)cBindingsAssignment_7_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Configuration_Impl Configuration:
		//	'Configuration'
		//	name=EString
		//	'{'
		//	components+=Component ("," components+=Component)* (connectors+=Connector ("," connectors+=Connector)*) (ports+=Port
		//	("," ports+=Port)*)* (bindings+=Binding ("," bindings+=Binding)*)*
		//	//(attachements+=Attachement ( "," attachements+=Attachement)* )
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Configuration' name=EString '{' components+=Component ("," components+=Component)* (connectors+=Connector (","
		//connectors+=Connector)*) (ports+=Port ("," ports+=Port)*)* (bindings+=Binding ("," bindings+=Binding)*)* //(attachements+=Attachement ( "," attachements+=Attachement)* )
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Configuration'
		public Keyword getConfigurationKeyword_0() { return cConfigurationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//components+=Component
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_0() { return cComponentsComponentParserRuleCall_3_0; }
		
		//("," components+=Component)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//components+=Component
		public Assignment getComponentsAssignment_4_1() { return cComponentsAssignment_4_1; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_4_1_0() { return cComponentsComponentParserRuleCall_4_1_0; }
		
		//connectors+=Connector ("," connectors+=Connector)*
		public Group getGroup_5() { return cGroup_5; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_5_0() { return cConnectorsAssignment_5_0; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_5_0_0() { return cConnectorsConnectorParserRuleCall_5_0_0; }
		
		//("," connectors+=Connector)*
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//","
		public Keyword getCommaKeyword_5_1_0() { return cCommaKeyword_5_1_0; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_5_1_1() { return cConnectorsAssignment_5_1_1; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_5_1_1_0() { return cConnectorsConnectorParserRuleCall_5_1_1_0; }
		
		//(ports+=Port ("," ports+=Port)*)*
		public Group getGroup_6() { return cGroup_6; }
		
		//ports+=Port
		public Assignment getPortsAssignment_6_0() { return cPortsAssignment_6_0; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_6_0_0() { return cPortsPortParserRuleCall_6_0_0; }
		
		//("," ports+=Port)*
		public Group getGroup_6_1() { return cGroup_6_1; }
		
		//","
		public Keyword getCommaKeyword_6_1_0() { return cCommaKeyword_6_1_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_6_1_1() { return cPortsAssignment_6_1_1; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_6_1_1_0() { return cPortsPortParserRuleCall_6_1_1_0; }
		
		//(bindings+=Binding ("," bindings+=Binding)*)*
		public Group getGroup_7() { return cGroup_7; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_7_0() { return cBindingsAssignment_7_0; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_7_0_0() { return cBindingsBindingParserRuleCall_7_0_0; }
		
		//("," bindings+=Binding)*
		public Group getGroup_7_1() { return cGroup_7_1; }
		
		//","
		public Keyword getCommaKeyword_7_1_0() { return cCommaKeyword_7_1_0; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_7_1_1() { return cBindingsAssignment_7_1_1; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_7_1_1_0() { return cBindingsBindingParserRuleCall_7_1_1_0; }
		
		////(attachements+=Attachement ( "," attachements+=Attachement)* )
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class Service_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Service_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cServiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Service_Impl Service:
		//	{Service}
		//	'Service'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Service} 'Service' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Service}
		public Action getServiceAction_0() { return cServiceAction_0; }
		
		//'Service'
		public Keyword getServiceKeyword_1() { return cServiceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class RequiredServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.RequiredService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequiredServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRequiredServiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//RequiredService:
		//	{RequiredService}
		//	'RequiredService'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{RequiredService} 'RequiredService' name=EString
		public Group getGroup() { return cGroup; }
		
		//{RequiredService}
		public Action getRequiredServiceAction_0() { return cRequiredServiceAction_0; }
		
		//'RequiredService'
		public Keyword getRequiredServiceKeyword_1() { return cRequiredServiceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ProvidedServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.ProvidedService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProvidedServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProvidedServiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//ProvidedService:
		//	{ProvidedService}
		//	'ProvidedService'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{ProvidedService} 'ProvidedService' name=EString
		public Group getGroup() { return cGroup; }
		
		//{ProvidedService}
		public Action getProvidedServiceAction_0() { return cProvidedServiceAction_0; }
		
		//'ProvidedService'
		public Keyword getProvidedServiceKeyword_1() { return cProvidedServiceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class Role_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Role_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRoleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Role_Impl Role:
		//	{Role}
		//	'Role'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Role} 'Role' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Role}
		public Action getRoleAction_0() { return cRoleAction_0; }
		
		//'Role'
		public Keyword getRoleKeyword_1() { return cRoleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class RequiredRoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.RequiredRole");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequiredRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRequiredRoleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//RequiredRole:
		//	{RequiredRole}
		//	'RequiredRole'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{RequiredRole} 'RequiredRole' name=EString
		public Group getGroup() { return cGroup; }
		
		//{RequiredRole}
		public Action getRequiredRoleAction_0() { return cRequiredRoleAction_0; }
		
		//'RequiredRole'
		public Keyword getRequiredRoleKeyword_1() { return cRequiredRoleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ProvidedRoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.ProvidedRole");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProvidedRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProvidedRoleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//ProvidedRole:
		//	{ProvidedRole}
		//	'ProvidedRole'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{ProvidedRole} 'ProvidedRole' name=EString
		public Group getGroup() { return cGroup; }
		
		//{ProvidedRole}
		public Action getProvidedRoleAction_0() { return cProvidedRoleAction_0; }
		
		//'ProvidedRole'
		public Keyword getProvidedRoleKeyword_1() { return cProvidedRoleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class GlueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.Glue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGlueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGlueKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Glue:
		//	{Glue}
		//	'Glue';
		@Override public ParserRule getRule() { return rule; }
		
		//{Glue} 'Glue'
		public Group getGroup() { return cGroup; }
		
		//{Glue}
		public Action getGlueAction_0() { return cGlueAction_0; }
		
		//'Glue'
		public Keyword getGlueKeyword_1() { return cGlueKeyword_1; }
	}
	public class RequiredPortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.RequiredPort");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequiredPortAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRequiredPortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//RequiredPort:
		//	{RequiredPort}
		//	'RequiredPort'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{RequiredPort} 'RequiredPort' name=EString
		public Group getGroup() { return cGroup; }
		
		//{RequiredPort}
		public Action getRequiredPortAction_0() { return cRequiredPortAction_0; }
		
		//'RequiredPort'
		public Keyword getRequiredPortKeyword_1() { return cRequiredPortKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ProvidedPortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.ProvidedPort");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProvidedPortAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProvidedPortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//ProvidedPort:
		//	{ProvidedPort}
		//	'ProvidedPort'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{ProvidedPort} 'ProvidedPort' name=EString
		public Group getGroup() { return cGroup; }
		
		//{ProvidedPort}
		public Action getProvidedPortAction_0() { return cProvidedPortAction_0; }
		
		//'ProvidedPort'
		public Keyword getProvidedPortKeyword_1() { return cProvidedPortKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class SimpleConfigurationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univnantes.asa.xtext.CosaDsl.SimpleConfiguration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSimpleConfigurationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cComponentsComponentParserRuleCall_3_0 = (RuleCall)cComponentsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cComponentsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cComponentsComponentParserRuleCall_4_1_0 = (RuleCall)cComponentsAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cConnectorsAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cConnectorsConnectorParserRuleCall_5_0_0 = (RuleCall)cConnectorsAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cCommaKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cConnectorsAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cConnectorsConnectorParserRuleCall_5_1_1_0 = (RuleCall)cConnectorsAssignment_5_1_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cPortsAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cPortsPortParserRuleCall_6_0_0 = (RuleCall)cPortsAssignment_6_0.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Keyword cCommaKeyword_6_1_0 = (Keyword)cGroup_6_1.eContents().get(0);
		private final Assignment cPortsAssignment_6_1_1 = (Assignment)cGroup_6_1.eContents().get(1);
		private final RuleCall cPortsPortParserRuleCall_6_1_1_0 = (RuleCall)cPortsAssignment_6_1_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cBindingsAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cBindingsBindingParserRuleCall_7_0_0 = (RuleCall)cBindingsAssignment_7_0.eContents().get(0);
		private final Group cGroup_7_1 = (Group)cGroup_7.eContents().get(1);
		private final Keyword cCommaKeyword_7_1_0 = (Keyword)cGroup_7_1.eContents().get(0);
		private final Assignment cBindingsAssignment_7_1_1 = (Assignment)cGroup_7_1.eContents().get(1);
		private final RuleCall cBindingsBindingParserRuleCall_7_1_1_0 = (RuleCall)cBindingsAssignment_7_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//SimpleConfiguration:
		//	'SimpleConfiguration'
		//	name=EString
		//	'{'
		//	components+=Component ("," components+=Component)* (connectors+=Connector ("," connectors+=Connector)*)* (ports+=Port
		//	("," ports+=Port)*)* (bindings+=Binding ("," bindings+=Binding)*)*
		//	//(attachements+=Attachement ( "," attachements+=Attachement)* )
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SimpleConfiguration' name=EString '{' components+=Component ("," components+=Component)* (connectors+=Connector (","
		//connectors+=Connector)*)* (ports+=Port ("," ports+=Port)*)* (bindings+=Binding ("," bindings+=Binding)*)* //(attachements+=Attachement ( "," attachements+=Attachement)* )
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'SimpleConfiguration'
		public Keyword getSimpleConfigurationKeyword_0() { return cSimpleConfigurationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//components+=Component
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_0() { return cComponentsComponentParserRuleCall_3_0; }
		
		//("," components+=Component)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//components+=Component
		public Assignment getComponentsAssignment_4_1() { return cComponentsAssignment_4_1; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_4_1_0() { return cComponentsComponentParserRuleCall_4_1_0; }
		
		//(connectors+=Connector ("," connectors+=Connector)*)*
		public Group getGroup_5() { return cGroup_5; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_5_0() { return cConnectorsAssignment_5_0; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_5_0_0() { return cConnectorsConnectorParserRuleCall_5_0_0; }
		
		//("," connectors+=Connector)*
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//","
		public Keyword getCommaKeyword_5_1_0() { return cCommaKeyword_5_1_0; }
		
		//connectors+=Connector
		public Assignment getConnectorsAssignment_5_1_1() { return cConnectorsAssignment_5_1_1; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_5_1_1_0() { return cConnectorsConnectorParserRuleCall_5_1_1_0; }
		
		//(ports+=Port ("," ports+=Port)*)*
		public Group getGroup_6() { return cGroup_6; }
		
		//ports+=Port
		public Assignment getPortsAssignment_6_0() { return cPortsAssignment_6_0; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_6_0_0() { return cPortsPortParserRuleCall_6_0_0; }
		
		//("," ports+=Port)*
		public Group getGroup_6_1() { return cGroup_6_1; }
		
		//","
		public Keyword getCommaKeyword_6_1_0() { return cCommaKeyword_6_1_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_6_1_1() { return cPortsAssignment_6_1_1; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_6_1_1_0() { return cPortsPortParserRuleCall_6_1_1_0; }
		
		//(bindings+=Binding ("," bindings+=Binding)*)*
		public Group getGroup_7() { return cGroup_7; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_7_0() { return cBindingsAssignment_7_0; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_7_0_0() { return cBindingsBindingParserRuleCall_7_0_0; }
		
		//("," bindings+=Binding)*
		public Group getGroup_7_1() { return cGroup_7_1; }
		
		//","
		public Keyword getCommaKeyword_7_1_0() { return cCommaKeyword_7_1_0; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_7_1_1() { return cBindingsAssignment_7_1_1; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_7_1_1_0() { return cBindingsBindingParserRuleCall_7_1_1_0; }
		
		////(attachements+=Attachement ( "," attachements+=Attachement)* )
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	
	
	private final ConfigurationElements pConfiguration;
	private final PortElements pPort;
	private final ServiceElements pService;
	private final RoleElements pRole;
	private final CompositeConfigurationElements pCompositeConfiguration;
	private final EStringElements pEString;
	private final ComponentElements pComponent;
	private final ConnectorElements pConnector;
	private final Port_ImplElements pPort_Impl;
	private final BindingElements pBinding;
	private final AttachementElements pAttachement;
	private final Configuration_ImplElements pConfiguration_Impl;
	private final Service_ImplElements pService_Impl;
	private final RequiredServiceElements pRequiredService;
	private final ProvidedServiceElements pProvidedService;
	private final Role_ImplElements pRole_Impl;
	private final RequiredRoleElements pRequiredRole;
	private final ProvidedRoleElements pProvidedRole;
	private final GlueElements pGlue;
	private final RequiredPortElements pRequiredPort;
	private final ProvidedPortElements pProvidedPort;
	private final SimpleConfigurationElements pSimpleConfiguration;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CosaDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pConfiguration = new ConfigurationElements();
		this.pPort = new PortElements();
		this.pService = new ServiceElements();
		this.pRole = new RoleElements();
		this.pCompositeConfiguration = new CompositeConfigurationElements();
		this.pEString = new EStringElements();
		this.pComponent = new ComponentElements();
		this.pConnector = new ConnectorElements();
		this.pPort_Impl = new Port_ImplElements();
		this.pBinding = new BindingElements();
		this.pAttachement = new AttachementElements();
		this.pConfiguration_Impl = new Configuration_ImplElements();
		this.pService_Impl = new Service_ImplElements();
		this.pRequiredService = new RequiredServiceElements();
		this.pProvidedService = new ProvidedServiceElements();
		this.pRole_Impl = new Role_ImplElements();
		this.pRequiredRole = new RequiredRoleElements();
		this.pProvidedRole = new ProvidedRoleElements();
		this.pGlue = new GlueElements();
		this.pRequiredPort = new RequiredPortElements();
		this.pProvidedPort = new ProvidedPortElements();
		this.pSimpleConfiguration = new SimpleConfigurationElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.univnantes.asa.xtext.CosaDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Configuration:
	//	Configuration_Impl | SimpleConfiguration | CompositeConfiguration;
	public ConfigurationElements getConfigurationAccess() {
		return pConfiguration;
	}
	
	public ParserRule getConfigurationRule() {
		return getConfigurationAccess().getRule();
	}
	
	//Port:
	//	Port_Impl | RequiredPort | ProvidedPort;
	public PortElements getPortAccess() {
		return pPort;
	}
	
	public ParserRule getPortRule() {
		return getPortAccess().getRule();
	}
	
	//Service:
	//	Service_Impl | RequiredService | ProvidedService;
	public ServiceElements getServiceAccess() {
		return pService;
	}
	
	public ParserRule getServiceRule() {
		return getServiceAccess().getRule();
	}
	
	//Role:
	//	Role_Impl | RequiredRole | ProvidedRole;
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//CompositeConfiguration:
	//	'CompositeConfiguration'
	//	name=EString
	//	'{' (components+=Component ("," components+=Component)*) (connectors+=Connector ("," connectors+=Connector)*)*
	//	(ports+=Port ("," ports+=Port)*)* (bindings+=Binding ("," bindings+=Binding)*)* (attachements+=Attachement (","
	//	attachements+=Attachement)*)* (configurations+=Configuration ("," configurations+=Configuration)*)*
	//	'}';
	public CompositeConfigurationElements getCompositeConfigurationAccess() {
		return pCompositeConfiguration;
	}
	
	public ParserRule getCompositeConfigurationRule() {
		return getCompositeConfigurationAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Component:
	//	'Component'
	//	name=EString
	//	'{'
	//	ports+=Port ("," ports+=Port)*
	//	services+=Service ("," services+=Service)*
	//	'}';
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//Connector:
	//	'Connector'
	//	name=EString
	//	'{'
	//	roles+=Role ("," roles+=Role)* ('glue' glue=Glue)?
	//	'}';
	public ConnectorElements getConnectorAccess() {
		return pConnector;
	}
	
	public ParserRule getConnectorRule() {
		return getConnectorAccess().getRule();
	}
	
	//Port_Impl Port:
	//	{Port}
	//	'Port'
	//	name=EString;
	public Port_ImplElements getPort_ImplAccess() {
		return pPort_Impl;
	}
	
	public ParserRule getPort_ImplRule() {
		return getPort_ImplAccess().getRule();
	}
	
	//Binding:
	//	'Binding'
	//	'('
	//	configurationProvider=[Configuration] '.' portProvided=[Port] ',' componentSubscriber=[Component] '.'
	//	portRequired=[Port]
	//	')';
	public BindingElements getBindingAccess() {
		return pBinding;
	}
	
	public ParserRule getBindingRule() {
		return getBindingAccess().getRule();
	}
	
	//Attachement:
	//	'Attachement'
	//	'{'
	//	component=[Component] '.' port=[Port] 'to' connector=[Connector] '.' role=[Role]
	//	'}';
	public AttachementElements getAttachementAccess() {
		return pAttachement;
	}
	
	public ParserRule getAttachementRule() {
		return getAttachementAccess().getRule();
	}
	
	//Configuration_Impl Configuration:
	//	'Configuration'
	//	name=EString
	//	'{'
	//	components+=Component ("," components+=Component)* (connectors+=Connector ("," connectors+=Connector)*) (ports+=Port
	//	("," ports+=Port)*)* (bindings+=Binding ("," bindings+=Binding)*)*
	//	//(attachements+=Attachement ( "," attachements+=Attachement)* )
	//	'}';
	public Configuration_ImplElements getConfiguration_ImplAccess() {
		return pConfiguration_Impl;
	}
	
	public ParserRule getConfiguration_ImplRule() {
		return getConfiguration_ImplAccess().getRule();
	}
	
	//Service_Impl Service:
	//	{Service}
	//	'Service'
	//	name=EString;
	public Service_ImplElements getService_ImplAccess() {
		return pService_Impl;
	}
	
	public ParserRule getService_ImplRule() {
		return getService_ImplAccess().getRule();
	}
	
	//RequiredService:
	//	{RequiredService}
	//	'RequiredService'
	//	name=EString;
	public RequiredServiceElements getRequiredServiceAccess() {
		return pRequiredService;
	}
	
	public ParserRule getRequiredServiceRule() {
		return getRequiredServiceAccess().getRule();
	}
	
	//ProvidedService:
	//	{ProvidedService}
	//	'ProvidedService'
	//	name=EString;
	public ProvidedServiceElements getProvidedServiceAccess() {
		return pProvidedService;
	}
	
	public ParserRule getProvidedServiceRule() {
		return getProvidedServiceAccess().getRule();
	}
	
	//Role_Impl Role:
	//	{Role}
	//	'Role'
	//	name=EString;
	public Role_ImplElements getRole_ImplAccess() {
		return pRole_Impl;
	}
	
	public ParserRule getRole_ImplRule() {
		return getRole_ImplAccess().getRule();
	}
	
	//RequiredRole:
	//	{RequiredRole}
	//	'RequiredRole'
	//	name=EString;
	public RequiredRoleElements getRequiredRoleAccess() {
		return pRequiredRole;
	}
	
	public ParserRule getRequiredRoleRule() {
		return getRequiredRoleAccess().getRule();
	}
	
	//ProvidedRole:
	//	{ProvidedRole}
	//	'ProvidedRole'
	//	name=EString;
	public ProvidedRoleElements getProvidedRoleAccess() {
		return pProvidedRole;
	}
	
	public ParserRule getProvidedRoleRule() {
		return getProvidedRoleAccess().getRule();
	}
	
	//Glue:
	//	{Glue}
	//	'Glue';
	public GlueElements getGlueAccess() {
		return pGlue;
	}
	
	public ParserRule getGlueRule() {
		return getGlueAccess().getRule();
	}
	
	//RequiredPort:
	//	{RequiredPort}
	//	'RequiredPort'
	//	name=EString;
	public RequiredPortElements getRequiredPortAccess() {
		return pRequiredPort;
	}
	
	public ParserRule getRequiredPortRule() {
		return getRequiredPortAccess().getRule();
	}
	
	//ProvidedPort:
	//	{ProvidedPort}
	//	'ProvidedPort'
	//	name=EString;
	public ProvidedPortElements getProvidedPortAccess() {
		return pProvidedPort;
	}
	
	public ParserRule getProvidedPortRule() {
		return getProvidedPortAccess().getRule();
	}
	
	//SimpleConfiguration:
	//	'SimpleConfiguration'
	//	name=EString
	//	'{'
	//	components+=Component ("," components+=Component)* (connectors+=Connector ("," connectors+=Connector)*)* (ports+=Port
	//	("," ports+=Port)*)* (bindings+=Binding ("," bindings+=Binding)*)*
	//	//(attachements+=Attachement ( "," attachements+=Attachement)* )
	//	'}';
	public SimpleConfigurationElements getSimpleConfigurationAccess() {
		return pSimpleConfiguration;
	}
	
	public ParserRule getSimpleConfigurationRule() {
		return getSimpleConfigurationAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
