/*
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.ui.tests;

import com.google.inject.Injector;
import fr.univnantes.asa.xtext.cosadsl.ui.internal.CosadslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CosaDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CosadslActivator.getInstance().getInjector("fr.univnantes.asa.xtext.CosaDsl");
	}

}
