/**
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.validation;

import fr.univnantes.asa.xtext.validation.AbstractCosaDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CosaDslValidator extends AbstractCosaDslValidator {
}
