/**
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.scoping;

import fr.univnantes.asa.cosa.Attachement;
import fr.univnantes.asa.cosa.Binding;
import fr.univnantes.asa.xtext.scoping.AbstractCosaDslScopeProvider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CosaDslScopeProvider extends AbstractCosaDslScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    if ((context instanceof Binding)) {
      return this.binding(((Binding)context), reference);
    } else {
      if ((context instanceof Attachement)) {
        return this.attachement(((Attachement)context), reference);
      }
    }
    return super.getScope(context, reference);
  }
  
  public IScope binding(final Binding context, final EReference reference) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field configurationProvider is undefined for the type Binding"
      + "\nThe method or field componentSubscriber is undefined for the type Binding"
      + "\nports cannot be resolved"
      + "\nports cannot be resolved");
  }
  
  public IScope attachement(final Attachement context, final EReference reference) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field component is undefined for the type Attachement"
      + "\nThe method or field connector is undefined for the type Attachement"
      + "\nports cannot be resolved"
      + "\nroles cannot be resolved");
  }
}
