/**
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.scoping;

import fr.univnantes.asa.xtext.scoping.AbstractCosaDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CosaDslScopeProvider extends AbstractCosaDslScopeProvider {
}
