/*
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext.ui;

import com.google.inject.Injector;
import fr.univnantes.asa.xtext.cosadsl.ui.internal.CosadslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CosaDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CosadslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CosadslActivator activator = CosadslActivator.getInstance();
		return activator != null ? activator.getInjector(CosadslActivator.FR_UNIVNANTES_ASA_XTEXT_COSADSL) : null;
	}

}
