package enums;

public enum Action {
    CLIENT_REQUEST,
    CLIENT_RESPONSE,
    SERVER_REQUEST,
    BACK_SERVER_REQUEST,
    SERVER_RESPONSE,
    RESOLVE_SERVER_REQUEST,
    BACK_RESOLVE_SERVER_REQUEST,
    RESOLVE_SERVER_RESPONSE,
    BD_QUERY,
    RESOLVE_BD_QUERY,
    CLEARENCE_REQUEST,
    RESOLVE_CLEARENCE_REQUEST,
    SECURITY_QUERY,
    RESOLVE_SECURITY_QUERY,
    RESPONSE_SECURITY_QUERY,
    ACCESS_GRANTED,
    BACK_RESOLVE_SECURITY_QUERY,
    BACK_SECURITY_QUERY,
    BACK_RESOLVE_CLEARENCE_REQUEST,
    SEND_DB_QUERY,
    RESOLVE_SEND_DB_QUERY,
    BACK_RESOLVE_SEND_DB_QUERY,
    BACK_SEND_DB_QUERY

}
