/**
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext;

import fr.univnantes.asa.xtext.AbstractCosaDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CosaDslRuntimeModule extends AbstractCosaDslRuntimeModule {
}
