/**
 * generated by Xtext 2.15.0
 */
package fr.univnantes.asa.xtext;

import fr.univnantes.asa.xtext.CosaDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CosaDslStandaloneSetup extends CosaDslStandaloneSetupGenerated {
  public static void doSetup() {
    new CosaDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
